### ISSUE TITLE
Installation problem: unable to re-encode 'myGSEAplot.R'

### ISSUE THREAD

**Issue by Iza410** [ShellyCoder/cellcall#4]
Thank you for this great package, but I have a problem with the installation. 
This message appears:

**Error : (converted from warning) unable to re-encode 'myGSEAplot.R' lines 16, 48, 55, 131, 132, 146
ERROR: unable to collate and parse R files for package 'cellcall'**

I checked what's in 'myGSEAplot.R' and I have no idea what the problem is.  
I will be grateful for any hint

**Comment by ShellyCoder** [comment]
Hi lza,

Not sure this issue, but i think the problem should be system language locale setting. I removed the comment of code not in English completely to avoid conflict. Try the latest commit... I hope that may help and sorry for the inconvenience.

best
Shelly

**Comment by Iza410** [comment]
Hi Shelly,

Comments were a problem, everything works now!!!

Thanks again for your help 

Best,
Iza
