### ISSUE TITLE
Error when using Viewintercircos

### ISSUE THREAD

**Issue by millersan** [ShellyCoder/cellcall#7]
I have met this error when I follow the pipeline using data from Seurat.

```
Error in if (any(factors == "")) { : 
  missing value where TRUE/FALSE needed
Calls: ViewInterCircos -> circos.initialize
Execution halted
```

**Comment by millersan** [comment]
Dear author,
I tried to downsample, but the data is still very large, sorry I may have difficulty emailing you.
By the way, I tried to observe the difference between the H data and the example data, and I found some interesting results.

Example data
![image](https://user-images.githubusercontent.com/46741428/131218411-a676b25f-5e76-4bf8-b410-a54f44822b19.png)
My data
![image](https://user-images.githubusercontent.com/46741428/131218411-a676b25f-5e76-4bf8-b410-a54f44822b19.png)
My data turn to cellcall data
![image](https://user-images.githubusercontent.com/46741428/131218438-a205aa02-4843-413b-85f5-2fc27af46573.png)

**Comment by ShellyCoder** [comment]
Hi, millersan,

Your file **dd_SCT.csv** in email was downloaded and processed locally.

I guess that the parameter` order.vector` in function `ViewInterCircos `should be `c("P1", "P3", "P5", "P7", "D1", "D3", "D5", "D7")` which represented your cell type stored in `H_cellcall@meta.data$celltype` and the colnames of `H_cellcall@data$expr_l_r_log2_scale` instead of `c("cluster_0","cluster_1","cluster_2","cluster_3","cluster_4","cluster_5")`.

> p <-ViewInterCircos(object = H_cellcall, font = 2, cellColor = cell_color,  lrColor = c("#F16B6F", "#84B1ED"),
                arr.type = "big.arrow",arr.length = 0.04, trackhight1 = 0.05, slot="expr_l_r_log2_scale",  linkcolor.from.sender = TRUE,
                linkcolor = NULL, gap.degree = 2,   order.vector=c("cluster_0","cluster_1","cluster_2","cluster_3","cluster_4","cluster_5"),
                trackhight2 = 0.032, track.margin2 = c(0.01,0.12), DIY = FALSE)	

And the figure run from my local environment has been attached.

best wishes.
Shelly.

![image](https://user-images.githubusercontent.com/49678387/131251082-530775a6-4e4f-4d20-8f7b-d667aa84cfde.png)

**Comment by millersan** [comment]
Dear author, thank you for your reply.
I entered the metadata of cluster1-5 in cell_type, and I changed the Idents to "new" before I entered it. 
c("P1", "P3", "P5", "P7", "D1", "D3", "D5", "D7") is the name used in the merge in seurat. So in the heat map, the LR-pathway is the information used in the "new", not the P/D.

**Comment by ShellyCoder** [comment]
Ah, not familar with your data. But i'm convinced that it also work on your settings, too.

Considering some personal changes by yourself, why not open DIY and just plot circle with the result dataframe? 

Set `DIY = TRUE`  and `object = yourDF` in the function as the below code. And keep the colnames of yourDF in the line with order.vector. For example, if your `order.vector = c('A', 'B')`, the colnames of `yourDF` should be total or subclass of { A-B, A-A, B-A, B-B }.

> yourDF <- H_cellcall@data$expr_l_r_log2_scale
> 
> ViewInterCircos(object = yourDF, font = 2, cellColor = cell_color, lrColor = c("#F16B6F", "#84B1ED"),
> arr.type = "big.arrow",arr.length = 0.04, trackhight1 = 0.05, slot="expr_l_r_log2_scale", linkcolor.from.sender = TRUE,
> linkcolor = NULL, gap.degree = 2, order.vector=c("cluster_0","cluster_1","cluster_2","cluster_3","cluster_4","cluster_5"),
> trackhight2 = 0.032, track.margin2 = c(0.01,0.12), DIY = TRUE)

Yours sincerely,
Shelly

**Comment by millersan** [comment]
Dear author, 
Following your instructions, I successfully got the graphics, thanks a lot!

**Comment by ShellyCoder** [comment]
Happy for your valuable response and great appreciations !
Shelly.
